from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="taco")
    parser.add_argument("--config", default="taco.yaml", help="config file path")
    parser.add_argument(
        "--human-context",
        action="store_true",
        help="render supported context responses as human-readable text",
    )

    domain_subparsers = parser.add_subparsers(dest="domain", required=True)
    domain_subparsers.add_parser("init")

    task_parser = domain_subparsers.add_parser("task")
    task_sub = task_parser.add_subparsers(dest="action", required=True)
    task_sub.add_parser("list")
    task_pack = task_sub.add_parser("pack")
    task_pack.add_argument("--task-id", required=False)
    task_pack.add_argument("--budget-tokens", type=int, default=None)

    task_targets = task_sub.add_parser("targets")
    task_targets.add_argument("--task-id", required=True)
    task_targets.add_argument("--route-type", required=True)

    task_record = task_sub.add_parser("record")
    task_record.add_argument("--task-id", required=True)
    task_record.add_argument("--route-type", required=True)
    record_content = task_record.add_mutually_exclusive_group(required=True)
    record_content.add_argument("--content")
    record_content.add_argument("--content-file")
    task_record.add_argument("--apply", action="store_true")

    task_complete = task_sub.add_parser("complete")
    task_complete.add_argument("--task-id", required=True)
    task_complete.add_argument("--implementation", required=True)
    task_complete.add_argument("--verification", required=True)
    task_complete.add_argument("--apply", action="store_true")

    task_block = task_sub.add_parser("block")
    task_block.add_argument("--task-id", required=True)
    task_block.add_argument("--reason-code", required=True)
    task_block.add_argument("--reason", required=True)
    task_block.add_argument("--apply", action="store_true")

    doc_parser = domain_subparsers.add_parser("doc")
    doc_sub = doc_parser.add_subparsers(dest="action", required=True)
    doc_snippet = doc_sub.add_parser("snippet")
    doc_snippet.add_argument("--path", required=True)
    doc_snippet.add_argument("--anchor-id", required=True)
    doc_section = doc_sub.add_parser("section")
    doc_section_sub = doc_section.add_subparsers(dest="doc_action", required=True)
    doc_section_get = doc_section_sub.add_parser("get")
    doc_section_get.add_argument("--path", required=True)
    doc_section_get.add_argument("--section-id", required=True)
    doc_section_patch = doc_section_sub.add_parser("patch")
    doc_section_patch.add_argument("--path", required=True)
    doc_section_patch.add_argument("--section-id", required=True)
    doc_section_patch.add_argument("--base-fingerprint", required=True)
    doc_section_patch.add_argument("--ops-json", required=True)
    doc_section_patch.add_argument("--apply", action="store_true")

    issue_parser = domain_subparsers.add_parser("issue")
    issue_sub = issue_parser.add_subparsers(dest="action", required=True)
    issue_triage = issue_sub.add_parser("triage")
    issue_triage.add_argument("--title", required=True)

    conv_parser = domain_subparsers.add_parser("convention")
    conv_sub = conv_parser.add_subparsers(dest="action", required=True)
    conv_get = conv_sub.add_parser("get")
    conv_get.add_argument("--topic", default="git")

    plan_parser = domain_subparsers.add_parser("plan")
    plan_sub = plan_parser.add_subparsers(dest="action", required=True)
    plan_pack = plan_sub.add_parser("pack")
    plan_pack.add_argument("--task-id", required=True)
    plan_pack.add_argument("--budget-tokens", type=int, default=None)
    plan_mode = plan_sub.add_parser("mode")
    plan_mode_sub = plan_mode.add_subparsers(dest="mode_action", required=True)
    plan_mode_guide = plan_mode_sub.add_parser("guide")
    plan_mode_guide.add_argument("--stage", required=False)

    plan_design = plan_sub.add_parser("design")
    plan_design_sub = plan_design.add_subparsers(dest="design_action", required=True)
    plan_design_submit = plan_design_sub.add_parser("submit-changes")
    plan_design_submit.add_argument("--changes-json", required=True)

    plan_task = plan_sub.add_parser("task")
    plan_task_sub = plan_task.add_subparsers(dest="plan_task_action", required=True)
    plan_task_template = plan_task_sub.add_parser("template")
    plan_task_template.add_argument("--intent-id", required=True)
    plan_task_template.add_argument("--task-id", required=False)
    plan_task_sync = plan_task_sub.add_parser("sync-frontmatter")
    plan_task_sync.add_argument("--intent-id", required=True)
    plan_task_sync.add_argument("--path", required=True)
    plan_task_sync.add_argument("--front-matter-json", required=False)
    plan_task_lint = plan_task_sub.add_parser("lint")
    plan_task_lint.add_argument("--path", required=True)
    plan_task_lint.add_argument("--intent-id", required=False)
    plan_task_submit = plan_task_sub.add_parser("submit-many")
    plan_task_submit.add_argument("--tasks-json", required=True)

    plan_intent = plan_sub.add_parser("intent")
    plan_intent_sub = plan_intent.add_subparsers(dest="intent_action", required=True)
    plan_intent_sub.add_parser("list")
    plan_intent_sub.add_parser("template")
    plan_intent_create_many = plan_intent_sub.add_parser("create-many")
    plan_intent_create_many.add_argument("--intents-json", required=True)
    plan_intent_create_many.add_argument("--plan-ref", required=False)
    plan_intent_submit_many = plan_intent_sub.add_parser("submit-many")
    plan_intent_submit_many.add_argument("--intents-json", required=True)
    plan_intent_submit_many.add_argument("--plan-ref", required=False)
    plan_intent_view = plan_intent_sub.add_parser("view")
    plan_intent_view.add_argument("--intent-id", required=True)
    plan_intent_index = plan_intent_sub.add_parser("index")
    plan_intent_index.add_argument("--intent-id", required=True)
    plan_intent_index.add_argument("--budget-tokens", type=int, default=None)
    plan_intent_validate = plan_intent_sub.add_parser("validate")
    plan_intent_validate.add_argument("--intent-id", required=True)
    plan_intent_propose = plan_intent_sub.add_parser("propose")
    plan_intent_propose.add_argument("--intent-id", required=False)
    plan_intent_propose.add_argument("--intent-text", required=False)
    plan_intent_propose.add_argument("--title", required=False)
    plan_intent_autodesign = plan_intent_sub.add_parser("autodesign")
    plan_intent_autodesign.add_argument("--intent-id", required=True)
    plan_intent_autodesign.add_argument("--proposal-fingerprint", required=True)
    plan_intent_generate = plan_intent_sub.add_parser("generate-tasks")
    plan_intent_generate.add_argument("--intent-id", required=True)
    plan_intent_generate.add_argument("--design-fingerprint", required=True)
    plan_intent_review = plan_intent_sub.add_parser("review-bundle")
    plan_intent_review.add_argument("--intent-id", required=True)
    plan_intent_review.add_argument("--proposal-fingerprint", required=True)
    plan_intent_review.add_argument("--design-fingerprint", required=True)
    plan_intent_review.add_argument("--taskset-fingerprint", required=True)
    plan_intent_review.add_argument("--retry-on-fail", type=int, default=0)
    plan_intent_apply = plan_intent_sub.add_parser("apply")
    plan_intent_apply.add_argument("--intent-id", required=True)
    plan_intent_apply.add_argument("--decision-fingerprint", required=True)
    plan_intent_apply.add_argument("--approve", action="store_true")
    plan_intent_apply.add_argument("--apply", action="store_true")
    plan_sub.add_parser("view")
    plan_locate = plan_sub.add_parser("locate")
    plan_locate.add_argument("--change-type", required=True)
    plan_locate.add_argument("--target", default="")
    plan_sub.add_parser("validate")

    build_parser = domain_subparsers.add_parser("build")
    build_sub = build_parser.add_subparsers(dest="action", required=True)
    build_precheck = build_sub.add_parser("precheck")
    build_precheck.add_argument("--pack-json", required=True)
    build_postcheck = build_sub.add_parser("postcheck")
    build_postcheck.add_argument("--pack-json", required=True)
    build_postcheck.add_argument("--changed-paths-json", default="[]")
    build_postcheck.add_argument("--produced-outputs-json", default="[]")
    build_postcheck.add_argument("--check-results-json", default="{}")

    return parser
